blank_issues_enabled: true
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/siguici/siguici/discussions/categories/q-a
    about: "Have a question? Start a discussion in the **Q&A** category."

  - name: 📄 Documentation Feedback
    url: https://github.com/siguici/siguici/issues/new
    about: "Have feedback or found an issue in the documentation? Open a documentation issue here."
