blank_issues_enabled: true
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/siguici/siguici/discussions
    about: "Got a question? We're happy to help! Start a discussion in the relevant category."

  - name: 📄 Documentation Feedback
    url: https://github.com/siguici/siguici/issues/new
    about: "Have feedback or found an issue in the documentation? Open a documentation issue here."
