blank_issues_enabled: false
contact_links:
  - name: Documentation issue
    url: https://github.com/siguici/siguici/issues/new/choose
    about: For documentation issues, open a pull request at the siguici/siguici repository
